---
title: "homework_04"
author: "Esteban Jorquera; Marlon Aldair; Diego Ramírez"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
  css: readable.min.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#### deeptools heatmap visualization of Human H3K36me3 ChIP data

```{code deeptools_H3K36me3.sge}
#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
# You can edit the script since this line
#
# Your job name
#$ -N Esteban_deeptools_H3K36me3

# Send an email after the job has finished
#$ -m e
#$ -M eijorquera@uc.cl
#
# Line required if modules are to be used, source modules environment
. /etc/profile.d/modules.sh
#
# Loads deeptools module,
# executes computeMatrix and plotHeatmap to generate a heatmap of human H3K36me3 ChIP-seq coverage
(module load deeptools/2.5.3 ; 
computeMatrix reference-point -S /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K36me3.bw -R /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/Human38_genesGencodev32.bed --referencePoint center -a 2000 -b 2000 -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_H3K36me3_matrix.tab.gz ; 
plotHeatmap -m /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_H3K36me3_matrix.tab.gz -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/output/H3K36me3_genes.png --heatmapHeight 15 --refPointLabel gene.center --regionsLabel genes --plotTitle ' H3K36me3 signal')
```

#### deeptools heatmap visualization of M. musculus Cebpa ChIP data

```{code}
# Downloads the mm10 annotation generated by UCSC which was uploaded to cyverse 
wget https://data.cyverse.org/dav-anon/iplant/home/estebanjorquera/mm10_NCBI_RefSeq.gz
```

```{code deeptools_CEBPA.sge}
#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
# You can edit the script since this line
#
# Your job name
#$ -N Esteban_deeptools_CEBPA

# Send an email after the job has finished
#$ -m e
#$ -M eijorquera@uc.cl
#
# Line required if modules are to be used, source modules environment
. /etc/profile.d/modules.sh
#
# Loads deeptools module,
# executes computeMatrix and plotHeatmap to generate a heatmap of mus musculus Cebpa ChIP-seq coverage
# centered at gene center and scaled to gene lenght
(module load deeptools/2.5.3 ; 
computeMatrix reference-point -S /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/MMusculus_CEBPA_ChIP_sort.bw -R /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/mm10_NCBI_RefSeq.bed.gz --referencePoint center -a 2000 -b 2000 -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_MMusculus_CEBPA_ChIP.tab.gz ; 
plotHeatmap -m /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_MMusculus_CEBPA_ChIP.tab.gz -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/output/CEBPA_genes.png --heatmapHeight 15 --refPointLabel gene.center --regionsLabel genes --plotTitle ' H3K36me3 signal' ;
computeMatrix scale-regions -S /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/MMusculus_CEBPA_ChIP_sort.bw -R /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/mm10_NCBI_RefSeq.bed.gz --startLabel TSS --endLabel TES -a 2000 -b 2000 -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_MMusculus_CEBPA_ChIP_scale.tab.gz ; 
plotHeatmap -m /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/matrix_MMusculus_CEBPA_ChIP_scale.tab.gz -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/output/CEBPA_genes_scale.png --heatmapHeight 15 --startLabel TSS --endLabel TES --regionsLabel genes --plotTitle ' H3K36me3 signal')
```


#### deeptools heatmap visualization of Human H3K27me3, H3K36me3, H3K4me3 ChIP data

```{code deeptools_HistoneMarks.sge}
#!/bin/bash
# Use current working directory
#$ -cwd
#
# Join stdout and stderr
#$ -j y
#
# Run job through bash shell
#$ -S /bin/bash
#
# You can edit the script since this line
#
# Your job name
#$ -N Esteban_deeptools_HistoneMarks

# Send an email after the job has finished
#$ -m e
#$ -M eijorquera@uc.cl
#
# Line required if modules are to be used, source modules environment
. /etc/profile.d/modules.sh
#
# Loads deeptools module,
# executes computeMatrix and plotHeatmap to generate a heatmap of human histone marks
(module load deeptools/2.5.3 ; 
computeMatrix scale-regions -S /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K27me3.bw /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K36me3.bw /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K4me3.bw -R /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/Human38_genesGencodev32.bed --beforeRegionStartLength 1000 --regionBodyLength 1000 --afterRegionStartLength 1000 --skipZeros -o matrix.mat.gz ; 
plotHeatmap -m matrix.mat.gz -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/output/HistoneMarkHeatmap.png)
```

(module load deeptools/2.5.3 ; 
computeMatrix scale-regions -S /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K27me3.bw /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K36me3.bw /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/H3K4me3.bw -R /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/Human38_genesGencodev32.bed --beforeRegionStartLength 1000 --regionBodyLength 1000 --afterRegionStartLength 1000 --skipZeros -o matrix.mat.gz ; 
plotHeatmap -m matrix.mat.gz -out /mnt/Citosina/amedina/ejorquera/BioInfoII/Tarea_4/output/HistoneMarkHeatmap.png)


computeMatrix scale-regions -S H3K27me3.bw H3K36me3.bw H3K4me3.bw -R Human38_genesGencodev39.bed --beforeRegionStartLength 1000 --regionBodyLength 1000 --afterRegionStartLength 1000 --skipZeros -o matrix.mat.gz ; 
plotHeatmap -m matrix.mat.gz -out ExampleHeatmap1.png)

